export type Priority = "ALTA" | "MEDIA" | "BAJA";

export type TriageCase = {
  id: string;
  patient: string;
  patientAge: number;
  priority: Priority;
  waitMinutes: number;
  summary: string;
  symptoms: string[];
  duration: string;
  history: string;
  submittedAt: string;
};

export const triageCases: TriageCase[] = [
  {
    id: "T-1284",
    patient: "Ernesto Vélez Ocampo",
    patientAge: 71,
    priority: "ALTA",
    waitMinutes: 2,
    summary: "Dolor torácico opresivo, sudoración, irradiación a brazo izquierdo",
    symptoms: ["Dolor torácico", "Sudoración", "Disnea"],
    duration: "Hace 30 minutos",
    history: "HTA controlada, EPOC GOLD 2, exfumador 20 años.",
    submittedAt: "2026-05-13T09:58",
  },
  {
    id: "T-1285",
    patient: "Camila Arboleda Restrepo",
    patientAge: 33,
    priority: "MEDIA",
    waitMinutes: 8,
    summary: "Dolor abdominal en fosa ilíaca derecha, náuseas, sin fiebre",
    symptoms: ["Dolor abdominal", "Náuseas"],
    duration: "Hace 6 horas",
    history: "Gastritis crónica. Última colonoscopia hace 2 años — normal.",
    submittedAt: "2026-05-13T09:52",
  },
  {
    id: "T-1286",
    patient: "Mateo Hincapié Sánchez",
    patientAge: 14,
    priority: "MEDIA",
    waitMinutes: 14,
    summary: "Fiebre 39.1°C, odinofagia, malestar general",
    symptoms: ["Fiebre", "Dolor de garganta", "Malestar general"],
    duration: "Hace 2 días",
    history: "Sin antecedentes relevantes. Vacunación al día.",
    submittedAt: "2026-05-13T09:46",
  },
  {
    id: "T-1287",
    patient: "Valentina Ruiz Henao",
    patientAge: 27,
    priority: "MEDIA",
    waitMinutes: 22,
    summary: "Cefalea pulsátil hemicraneal con fotofobia",
    symptoms: ["Cefalea", "Fotofobia"],
    duration: "Hace 4 horas",
    history: "Migraña con aura conocida. Tratamiento profiláctico irregular.",
    submittedAt: "2026-05-13T09:38",
  },
  {
    id: "T-1288",
    patient: "Antonia Pérez Gallego",
    patientAge: 64,
    priority: "ALTA",
    waitMinutes: 31,
    summary: "Palpitaciones, mareo y disnea de esfuerzo",
    symptoms: ["Palpitaciones", "Mareo", "Disnea"],
    duration: "Hace 1 hora",
    history: "Arritmia conocida. Holter reciente con FA paroxística.",
    submittedAt: "2026-05-13T09:29",
  },
  {
    id: "T-1289",
    patient: "Sara Lopera Cardona",
    patientAge: 24,
    priority: "BAJA",
    waitMinutes: 47,
    summary: "Tos seca persistente, sin fiebre ni disnea",
    symptoms: ["Tos"],
    duration: "Hace 10 días",
    history: "Sin antecedentes. No fuma.",
    submittedAt: "2026-05-13T09:13",
  },
  {
    id: "T-1290",
    patient: "Daniel Quintero Gómez",
    patientAge: 49,
    priority: "MEDIA",
    waitMinutes: 58,
    summary: "Astenia marcada, palidez, palpitaciones al esfuerzo",
    symptoms: ["Fatiga", "Palpitaciones"],
    duration: "Hace 3 semanas",
    history: "Anemia ferropénica en estudio.",
    submittedAt: "2026-05-13T09:02",
  },
  {
    id: "T-1291",
    patient: "Felipe Cárdenas Soto",
    patientAge: 36,
    priority: "BAJA",
    waitMinutes: 72,
    summary: "Dolor lumbar mecánico tras esfuerzo",
    symptoms: ["Dolor lumbar"],
    duration: "Hace 2 días",
    history: "Sin antecedentes osteomusculares.",
    submittedAt: "2026-05-13T08:48",
  },
  {
    id: "T-1292",
    patient: "Laura Posada Naranjo",
    patientAge: 38,
    priority: "MEDIA",
    waitMinutes: 91,
    summary: "Aumento de peso reciente, intolerancia al frío, fatiga",
    symptoms: ["Fatiga", "Aumento de peso"],
    duration: "Hace 2 meses",
    history: "Hipotiroidismo en tratamiento, última TSH hace 4 meses.",
    submittedAt: "2026-05-13T08:29",
  },
  {
    id: "T-1293",
    patient: "Joaquín Patiño Álvarez",
    patientAge: 12,
    priority: "BAJA",
    waitMinutes: 104,
    summary: "Sibilancias leves, sin compromiso respiratorio",
    symptoms: ["Sibilancias"],
    duration: "Hace 1 día",
    history: "Asma bronquial leve persistente, controlado.",
    submittedAt: "2026-05-13T08:16",
  },
  {
    id: "T-1294",
    patient: "Lucía Bustamante Toro",
    patientAge: 78,
    priority: "ALTA",
    waitMinutes: 117,
    summary: "Desorientación temporo-espacial, marcha inestable",
    symptoms: ["Confusión", "Marcha inestable"],
    duration: "Hace 12 horas",
    history: "Demencia tipo Alzheimer GDS 4, HTA.",
    submittedAt: "2026-05-13T08:03",
  },
  {
    id: "T-1295",
    patient: "Nicolás Madrid Sierra",
    patientAge: 22,
    priority: "BAJA",
    waitMinutes: 138,
    summary: "Inflamación de tobillo derecho post-esguince",
    symptoms: ["Inflamación articular"],
    duration: "Hace 5 días",
    history: "Esguince grado II diagnosticado hace una semana.",
    submittedAt: "2026-05-13T07:42",
  },
];